-- LUMA / SUPABASE
-- Ejecuta este script en Supabase > SQL Editor.

create table if not exists public.visitas (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    pagina text not null,
    evento text not null check (evento in ('entrada', 'salida')),
    session_id text not null,
    user_agent text
);

alter table public.visitas enable row level security;

-- El navegador solo puede INSERTAR registros.
-- No permitimos que visitantes anónimos lean los registros.
drop policy if exists "visitas_anon_insert" on public.visitas;
create policy "visitas_anon_insert"
on public.visitas
for insert
to anon
with check (evento in ('entrada', 'salida'));

-- El panel de administración podrá leer cuando el usuario esté autenticado.
drop policy if exists "visitas_authenticated_select" on public.visitas;
create policy "visitas_authenticated_select"
on public.visitas
for select
to authenticated
using (true);

-- Permisos mínimos para el Data API.
grant insert on public.visitas to anon;
grant select on public.visitas to authenticated;

-- Necesario para que la columna identity pueda asignar IDs al insertar.
grant usage, select on sequence public.visitas_id_seq to anon;
